//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class ValueMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Value";
        public override string RosMessageName => k_RosMessageName;

        public int val;

        public ValueMsg()
        {
            this.val = 0;
        }

        public ValueMsg(int val)
        {
            this.val = val;
        }

        public static ValueMsg Deserialize(MessageDeserializer deserializer) => new ValueMsg(deserializer);

        private ValueMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.val);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.val);
        }

        public override string ToString()
        {
            return "ValueMsg: " +
            "\nval: " + val.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
